# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='customer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
